INSERT INTO pais (nombre) VALUES ('colombia');
INSERT INTO pais (nombre) VALUES ('venezuela');
INSERT INTO pais (nombre) VALUES ('argentina');
INSERT INTO pais (nombre) VALUES ('peru');
INSERT INTO pais (nombre) VALUES ('ecuador');
INSERT INTO pais (nombre) VALUES ('UK');
INSERT INTO pais (nombre) VALUES ('US');
INSERT INTO pais (nombre) VALUES ('Francia');
INSERT INTO pais (nombre) VALUES ('Alemania');
INSERT INTO pais (nombre) VALUES ('Italia');
INSERT INTO provincia (id_pais, provincia) VALUES (1, 'Valle');
INSERT INTO provincia (id_pais, provincia) VALUES (1, 'Antioquia');
INSERT INTO provincia (id_pais, provincia) VALUES (1, 'Cundinamarca');
